name: BedwarsLobby
main: ro.marius.bedwars.BedwarsLobbyPlugin
author: Marius
description: ${project.parent.description}
version: ${project.parent.version}
api-version: 1.13
softdepend: [Citizens, PlaceholderAPI, Parties]